/**
 * Banque d'articles de presse pour la Partie 1 (avis argumenté) de TBS
 * Education. Sélection constituée par Robin/The Prepboard à titre d'entraînement —
 * ce n'est PAS la liste officielle de TBS (fournie aux candidats admissibles
 * sur leur espace candidat après les résultats d'admissibilité). À mettre à
 * jour dans le temps. Tous les articles ont été vérifiés en accès gratuit
 * intégral (pas de paywall) au moment de leur ajout.
 */
export interface TbsArticle {
  id: string;
  title: string;
  source: string;
  date: string;
  url: string;
  summary: string;
}

export const TBS_ARTICLES: TbsArticle[] = [
  { id: "tbs-01", title: "Bienvenue en gérontocratie : comment les retraités ont amassé argent et pouvoir", source: "Slate.fr", date: "2026-04-20", url: "https://www.slate.fr/economie/gerontocratie-retraites-pouvoir-argent-amasse-etats-unis-france-personnes-agees-politique-generation-chomage-inflation", summary: "Les seniors ont concentré une part croissante du patrimoine et du pouvoir politique (75% de la richesse US détenue par les 55 ans et plus ; en France, les retraités possèdent 60% du patrimoine national, 75% sont propriétaires). L'article mobilise le concept de « gérontonomie » et présente, sans trancher, des pistes de correction (âge de départ obligatoire, taxation du patrimoine, réorientation vers la jeunesse)." },
  { id: "tbs-02", title: "La génération Z est complètement paumée dans le monde de l'entreprise, mais ce n'est pas de sa faute", source: "Slate.fr", date: "2026-03-05", url: "https://www.slate.fr/societe/gen-z-paumee-travail-entreprises-codes-distance-ecrans-jeunes-actifs-professionnels-regles-accompagnement-pedagogie-teletravail-confinement", summary: "Les difficultés d'intégration professionnelle de la Gen Z s'expliquent par un déficit d'apprentissage informel des codes sociaux, aggravé par le confinement et les cours à distance. Position équilibrée : sans dédouaner les jeunes actifs, l'article appelle les entreprises à expliciter des normes jusque-là tacites plutôt qu'à sanctionner." },
  { id: "tbs-03", title: "Votre patron veut vous faire revenir au bureau et ce n'est pas que pour vous surveiller (c'est pire)", source: "Slate.fr", date: "2026-06-23", url: "https://www.slate.fr/societe/patron-revenir-bureau-surveiller-ego-narcissisme-travail-employe-teletravail-pouvoir-economie", summary: "Les mandats de retour au bureau à 100% relèveraient davantage du narcissisme managérial que d'une nécessité productive : le travail hybride améliorerait satisfaction et rétention sans nuire à la productivité." },
  { id: "tbs-04", title: "Semaine de quatre jours : l'IA ouvre la voie à un nouveau partage du travail", source: "Novethic", date: "2026-03-16", url: "https://www.novethic.fr/economie-et-social/transformation-de-leconomie/semaine-quatre-jours-democratisation-ia-entreprises-rebat-cartes", summary: "Une vingtaine d'entreprises françaises testent la semaine de 4 jours sans baisse de salaire (47% des salariés en détresse psychologique selon Empreinte humaine 2025). Thèse : les gains de productivité liés à l'IA devraient être redistribués en temps libre plutôt qu'en intensification du travail." },
  { id: "tbs-05", title: "Vous commandez à manger sur des plateformes ? Sachez que les conditions de travail des livreurs sont indignes", source: "Slate.fr", date: "2026-04-02", url: "https://www.slate.fr/economie/vous-commandez-repas-plateformes-conditions-travail-livreurs-indignes-uber-eats-deliveroo-etude-uberisation-precarite", summary: "Étude IRD/INED sur plus de 1000 livreurs à Paris et Bordeaux : 63h/semaine pour 5,83€ brut/h, 97,8% de travailleurs immigrés dont une majorité sans papiers. Dénonce une précarité organisée par le management algorithmique." },
  { id: "tbs-06", title: "Le recrutement sans CV est-il le futur du monde du travail ?", source: "Slate.fr", date: "2023-11-21", url: "https://www.slate.fr/story/256530/trouver-travail-recrutement-sans-cv-emploi-ressources-humaines-entretien-simulation", summary: "Pratiques de recrutement « sans CV » (Castorama, Accor) fondées sur des mises en situation, visant à réduire les biais mais coûteuses à généraliser, sans preuve d'une diversité effective accrue." },
  { id: "tbs-07", title: "Où l'intelligence artificielle mène-t-elle le monde ? C'est la grande inconnue", source: "Slate.fr", date: "2026-03-06", url: "https://www.slate.fr/economie/intelligence-artificielle-mene-monde-grande-inconnue-ia-doutes-avenir-menaces-bourse-emploi-ethique-humains-technologie", summary: "Capitalisation de Nvidia entre 4400 et 5000 milliards de dollars, 700 milliards investis en data centers en 2026. La FMI alerte sur 60% des emplois des pays développés affectés par l'IA ; responsables politiques mal préparés." },
  { id: "tbs-08", title: "Regardez ce qu'il se passe à Wall Street, vous y verrez l'avenir du monde", source: "Slate.fr", date: "2026-06-05", url: "https://www.slate.fr/economie/regardez-wall-street-vous-verrez-avenir-monde-bourse-new-york-nasdaq-records-milliards-nvidia-spacex-musk-energie-ia-politique-etats-unis", summary: "Domination boursière américaine (75 000 milliards $ de capitalisation contre 14 800 pour la Chine) portée par énergie et IA. Thèse critique : cette concentration de richesse sert une stratégie de puissance géopolitique plus qu'elle ne tient les promesses présidentielles." },
  { id: "tbs-09", title: "L'économie des Birkenstock, un gigantesque marché de dupes", source: "Slate.fr", date: "2026-07-18", url: "https://www.slate.fr/economie/sandales-iconiques-copiees-partout-monde-gigantesque-marche-dupes-birkenstock-chaussures-imitations-droit-auteur-mode-luxe-consommation", summary: "Décisions judiciaires contradictoires en Europe sur la protection du design Birkenstock par le droit d'auteur (70 ans après la mort du créateur vs 25 ans pour les brevets). Position critique envers une protection jugée excessive, freinant l'innovation et le choix du consommateur." },
  { id: "tbs-10", title: "Installer des panneaux solaires verticaux en guise de clôture peut paraître complètement débile, et pourtant", source: "Slate.fr", date: "2026-09-03", url: "https://www.slate.fr/economie/clotures-solaires-soleil-innovation-electricite-jardin-technologie-transition-energetique", summary: "Clôtures solaires verticales bifaciales (Next2Sun, 479 installations dans 6 pays) : jusqu'à +27% de production le matin selon une étude de l'université de York. Innovation présentée comme sous-exploitée." },
  { id: "tbs-11", title: "Feuille de route énergétique : un délicat équilibre à trouver en raison du contexte politique en France", source: "Slate.fr", date: "2026-02-20", url: "https://www.slate.fr/economie/grandes-lignes-feuille-route-energie-france-equilibre-contexte-politique-choix-mix-renouvelable-nucleaire-ppe3-programmation-pluriannuelle", summary: "La PPE3 (publiée le 13/02/2026) vise 380 TWh de nucléaire en 2030, EPR2 estimés à 72,8 milliards d'euros. Position critique : coût croissant du nucléaire face à la baisse continue du coût des renouvelables — un choix plus politique qu'économique." },
  { id: "tbs-12", title: "De canicule en sécheresse, la question climatique va-t-elle enfin être prise au sérieux par la classe politique ?", source: "Slate.fr", date: "2026-08-14", url: "https://www.slate.fr/economie/canicule-secheresse-probleme-pris-serieux-classe-politique-accord-paris-ecologie-changement-climatique", summary: "Cinquième canicule française de l'année, +1,47°C par rapport à 1850-1900 en juillet ; seuls 32% des Français citent l'environnement comme priorité contre 47% pour le pouvoir d'achat. Dénonce le paradoxe de gouvernements accélérant l'IA sans considération écologique équivalente." },
  { id: "tbs-13", title: "Un champignon jaune venu d'Asie envahit les forêts européennes, et c'est un problème", source: "Slate.fr", date: "2026-08-30", url: "https://www.slate.fr/sciences/culture-champignons-kits-invasif-pleurote-asie-europe-danger-ecosyseme-foret-colonisation", summary: "Le pleurote doré, déjà présent sur 2 millions de km² dans 25 États américains, se propage en Europe via des kits de culture domestique. Appelle à suspendre leur vente et à renforcer la réglementation." },
  { id: "tbs-14", title: "Comment les poulets ont conquis le monde en quelques décennies seulement", source: "Slate.fr", date: "2026-08-27", url: "https://www.slate.fr/boire-manger/poulet-consommation-mondiale-production-elevage-mondialisation-viande-volaille-tendance", summary: "76 milliards de volailles produites en 2023 contre 48 milliards en 2006, le Brésil dominant les exportations. Ton analytique, réserves finales sur les conditions d'élevage intensif et les limites environnementales du secteur." },
  { id: "tbs-15", title: "Avion en illimité : quand prendra-t-on vraiment en compte le coût carbone de nos voyages ?", source: "Slate.fr", date: "2024-08-25", url: "https://www.slate.fr/story/267971/avion-illimite-prendre-en-compte-cout-carbone-voyages-transport-aerien-podcast-france-2050", summary: "Abonnement Wizz Air « vols illimités » (599€/an) critiqué : l'aviation représente 7% des déplacements des Français mais plus de 50% des émissions CO2 liées aux transports. Rejette le « techno-solutionnisme » au profit d'un quota carbone individuel." },
  { id: "tbs-16", title: "Comment les destinations populaires à travers le monde s'organisent pour lutter contre le surtourisme", source: "Slate.fr", date: "2026-02-21", url: "https://www.slate.fr/societe/tourisme-comment-destinations-populaires-lutter-contre-surtourisme-taxes-interdiction-repression-recompense", summary: "Comparaison de cinq stratégies (répression japonaise, taxation américaine, incitations jamaïcaines, guidage algorithmique espagnol, CopenPay danois). Traitement neutre : aucune solution unique ne s'impose." },
  { id: "tbs-17", title: "Il est grand temps que le logement soit placé en tête des priorités politiques de la France", source: "Slate.fr", date: "2026-02-06", url: "https://www.slate.fr/economie/france-grand-temps-logement-redevienne-priorite-politique-crise-immobilier-construction-prix-plan-relance-logements-sociaux", summary: "350 000 personnes sans domicile, 2,8 millions de ménages en attente de logement social, seulement 274 611 logements construits en 2025. Soutient explicitement le plan « Relance logement », en avertissant sur son coût budgétaire." },
  { id: "tbs-18", title: "L'immigration pourrait tout à fait favoriser le développement économique de la France", source: "Slate.fr", date: "2024-01-16", url: "https://www.slate.fr/story/259017/tribune-immigration-politique-equilibree-favoriser-developpement-economique-france-polemiques", summary: "Tribune argumentée par les données : population étrangère en France (7,8% en 2022) comparable à l'Allemagne (13,1%) ; l'INSEE anticipe -50 000 actifs/an après 2040. Propose trois principes : piloter les flux, garantir une intégration digne, lutter contre l'irrégularité tout en régularisant les travailleurs en emploi." },
  { id: "tbs-19", title: "Puberté 2.0 : quand les réseaux sociaux façonnent le corps et l'estime des jeunes filles", source: "Slate.fr", date: "2025-06-27", url: "https://www.slate.fr/societe/puberte-reseaux-sociaux-corps-estime-jeunes-filles-complexe-tiktok-education-plateforme-parents-corps", summary: "Une fille sur trois éprouve des émotions négatives hebdomadaires liées au corps à cause de contenus en ligne ; l'insatisfaction corporelle passe de 53% à 13 ans à 78% à 17 ans. Appelle à une refonte de l'accompagnement associant écoles, plateformes et familles." },
  { id: "tbs-20", title: "Wegovy, Mounjaro, Saxenda : les nouveaux traitements contre l'obésité séduisent aussi les Français", source: "Slate.fr", date: "2026-02-05", url: "https://www.slate.fr/sante/wegovy-mounjaro-saxenda-nouveaux-traitements-contre-obesite-seduisent-francais-medicaments-analogues-glp-1-perte-poids-prix-remboursement", summary: "Adoption rapide des médicaments GLP-1 (ventes de Mounjaro x4 entre février et juin 2025), coût mensuel de 200 à 400€ non remboursé. Petite révolution sanitaire, mais inégalité d'accès selon les revenus." },
  { id: "tbs-21", title: "Shein : pourquoi le géant de l'ultra fast fashion est en train de flopper sévèrement", source: "Slate.fr", date: "2026-09-01", url: "https://www.slate.fr/economie/shein-entree-bourse-ratee-chine-colis-ultra-fast-fashion-gen-z-mode-prix-controverses-conditions-travail", summary: "IPO ratée à Hong Kong (valorisation à un quart de son niveau de 2022, -10% le premier jour) malgré 38 milliards $ de CA en 2025. Conditions de travail dénoncées dans les usines du Guangdong, désaffection Gen Z, nouvelles taxes européennes sur les petits colis." },
  { id: "tbs-22", title: "Quand un simple t-shirt blanc devient tellement luxueux qu'il peut coûter plus de 500 euros", source: "Slate.fr", date: "2026-08-15", url: "https://www.slate.fr/economie/quiet-luxury-shirt-blanc-prix-cher-marketing-luxe", summary: "Le « quiet luxury » : en l'absence de logo visible, les marques créent la perception de valeur via des signaux de prestige indirects. Analyse psychologique neutre du marketing du luxe minimaliste." },
  { id: "tbs-23", title: "La Chine n'a jamais produit autant et elle n'a plus vraiment besoin de ses ouvriers", source: "Slate.fr", date: "2026-09-03", url: "https://www.slate.fr/monde/chine-production-ouvriers-main-oeuvre-industrie-essor-technologies-pib-emploi", summary: "PIB chinois plus que doublé en dix ans, excédent commercial record (~1200 milliards $ en 2025), mais 14 millions d'emplois BTP perdus 2021-2025 par automatisation. La croissance technologique ne profite pas aux travailleurs manuels." },
  { id: "tbs-24", title: "Coupe du monde 2026 : financièrement, qui a touché le gros lot ?", source: "Slate.fr", date: "2026-07-20", url: "https://www.slate.fr/sports/coupe-du-monde-2026-recettes-financieres-mondial-fifa-football-argent", summary: "~15 milliards $ de revenus FIFA sur le cycle, billets revendus jusqu'à 2 millions $. Les grands acteurs (FIFA, diffuseurs, sponsors) ont largement bénéficié, mais les supporters ont subi une explosion des prix et les retombées pour les villes hôtes sont surestimées." },
];
